name: Run Shared Setup
description: Setup the shared environment

inputs:
  php-version:
    description: The PHP version to install
    default: 8.3

runs:
  using: composite
  steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1 # 2.36.0
      with:
        php-version: ${{ inputs.php-version }}
        tools: composer:v2
        coverage: none

    - name: Install Composer Dependencies
      shell: bash
      run: composer install --prefer-dist --no-progress --ignore-platform-reqs

    - name: Setup PNPM
      uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
      with:
        version: latest

    - name: Setup Node.js
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version-file: package.json
        cache: pnpm

    - name: Install Dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
